name: Deploy Flask to Azure App Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  OWM_API_KEY: ${{ secrets.OWM_API_KEY }}  # Simpan API Key sebagai secret di GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

    - name: Set API Key in Azure
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az webapp config appsettings set \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group my-flask-group \
            --settings OWM_API_KEY="${{ secrets.OWM_API_KEY }}"
