- name: Deploy to Azure
  uses: azure/webapps-deploy@v2
  with:
    app-name: 'weatherprojek'
    publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
    package: .  # Deploy seluruh folder
    # atau tentukan folder spesifik:
    # package: ${{ github.workspace }}/output
